server:
  port: 8080

# Logging settings.
debug: true

logging:
  level:
    org.springframework:
      security: DEBUG
    com.github.sahara3: DEBUG

# Spring settings.
spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    driver-class-name: org.h2.Driver
    username: sa

  session:
    store-type: hash-map

# Database settings.
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

flyway:
  enabled: false
  baseline-on-migrate: true
  baseline-version: 0

# Security settings.
security:
  basic:
    enabled: false

ssolite:
  server:
    enabled: true
    default-top-page-url: internal:/
    permitted-domains:
    - http://127.0.0.1:8081/sso-login
