server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

# Logging settings.
debug: true

logging:
  level:
    org.springframework:
      security: DEBUG
    com.github.sahara3: DEBUG

# SSOLite settings.
ssolite:
  server:
    enabled: true
    default-top-page-url: internal:/
    permitted-domains:
    - http://127.0.0.1:8081/sso-login
