server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'

# Logging settings.
debug: true

logging:
  level:
    org.springframework:
      security: DEBUG
    com.github.sahara3: DEBUG

# SSOLite settings.
ssolite:
  client:
    login-url: http://localhost:8080/login
    token-api-url: http://localhost:8080/api/tokens
    same-domain: false
