# Creates SSOLite release, and uploads artifacts to Maven Central.

name: SSOLite release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Show Gradle version
      run: ./gradlew -v
    - name: Make sure the version is not SNAPSHOT
      run: >-
        ./gradlew --console=plain ssolite-core:showVersion -q
        | grep -v -e '-SNAPSHOT$'

    - name: Build with Gradle
      run: ./gradlew --console=plain build

    - name: Upload artifacts to Maven Central
      run: >-
        ./gradlew --console=plain publish
        -Pmaven.sonatype.url=https://oss.sonatype.org/service/local/staging/deploy/maven2/
        -Pmaven.sonatype.username=${{ secrets.SONATYPE_USERNAME }}
        -Pmaven.sonatype.password=${{ secrets.SONATYPE_PASSWORD }}
      env:
        ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.PGP_ARMORED_PRIVATE_KEY }}
        ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.PGP_PASSWORD }}
        ORG_GRADLE_PROJECT_SIGNING_KEY_ID: ${{ secrets.PGP_KEY_ID }}

    - uses: actions/create-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          Update version to ${{ github.ref }}
        draft: true
        prerelease: true
