# Creates SSOLite release, and uploads artifacts to Bintray.

name: SSOLite release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Show Gradle version
      run: ./gradlew -v
    - name: Make sure the version is not SNAPSHOT
      run: >-
        ./gradlew ssolite-core:showVersion -q --console plain
        | grep -v -e '-SNAPSHOT$'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload artifacts to Bintray
      run: >-
        ./gradlew bintrayUpload
        -Pbintray.username=${{ secrets.BINTRAY_USER }}
        -Pbintray.apikey=${{ secrets.BINTRAY_APIKEY }}

    - uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          Update version to ${{ github.ref }}
        draft: true
        prerelease: true
